### ISSUE TITLE
travis-ci.org shutting down

### ISSUE THREAD

**Issue by jackrosenthal** [jackrosenthal/kajiki#53]
The CI system appears to have a scary banner on it that it may be shutting down in a few days:

> Hi! It seems there are still plenty of builds running. We're pushing back the shutdown date to June 15th. Please consider migrating to travis-ci.com.

Does something need done by the repo admins here to move it to travis-ci.com?

**Comment by amol-** [comment]
I think this is up to @nandoflorestan 
Probably the owner of the project must do this from https://travis-ci.org/account/repositories

**Comment by jackrosenthal** [comment]
Got it migrated to https://travis-ci.com/jackrosenthal/kajiki :)
