### ISSUE TITLE
migrate to pytest?

### ISSUE THREAD

**Issue by jackrosenthal** [jackrosenthal/kajiki#54]
nose v1 hasn't seen any new updates since 2016, and compatibility appears to be broken in Python 3.10.

pytest is the hot thing these days, and appears to already find and run the tests just fine...

switch the test runner from nose to pytest?

**Comment by amol-** [comment]
Given that I didn't see any real need for pytest (the test suite is fairly basic with nearly no fixtures) I was originally thinking of switching kajiki to just standard library unittest (`unittest discover`). I recently did the same for Ming ( https://github.com/TurboGears/Ming/commit/77fc3fc6918fee28beff8299302379d1ba1da09b ) and it worked fairly well.

I think it has the benefit of not depending on any external framework / dependency and works fairly well for libraries that don't have complex fixture needs like Kajiki.

I'm not against pytest anyway if you want to migrate to pytest.
