### ISSUE TITLE
drop support for Python 2.6, 2.7, 3.0-3.3?

### ISSUE THREAD

**Issue by jackrosenthal** [jackrosenthal/kajiki#55]
There's considerable cleanup that could be done if we stop supporting these versions of Python.

These days they are probably mostly antiques... any oppositions to dropping them?

**Comment by jackrosenthal** [comment]
Update here: going to push a 0.8.3 release, which will be the last release with support for Python 3.3 and older (including Python 2).

Release 0.9 will not support Python 2.6-3.3.

**Comment by jackrosenthal** [comment]
Latest master branch now requires 3.4+

**Comment by amol-** [comment]
Note that this might be a problem for TurboGears which uses Kajiki as the default template engine.

I refrained dropping support for Python2.7 in the past until TG2.5 was out as TurboGears still supports Python2.7 in 2.4.X. According to pypi stats, 2.7 still accounts for 10% of all package installs, so there is still a relevant chunk of users on it out there.

I think people can still install and use TurboGears on PY2.7 with Kajiki 0.8.X, Let's just make sure we backport for 0.8 any bugfixes for a little while if we end up making 0.9 incompatible with 2.7

**Comment by jackrosenthal** [comment]
Sure, the numbers look low for 2.7 on kajiki:

```
SELECT
  FORMAT("%s.%s", pyver_a[SAFE_OFFSET(0)], pyver_a[SAFE_OFFSET(1)]) AS pyver,
  COUNT(*) AS num_downloads
FROM (
  SELECT
    SPLIT(details.python, ".") AS pyver_a
  FROM
    `bigquery-public-data.pypi.file_downloads`
  WHERE
    file.project = 'kajiki'
    -- Users downloading a pinned old version from before 2019 don't count
    AND (file.version = "0.8.2"
      OR file.version = "0.8.3")
    -- Only query the last 30 days
    AND DATE(timestamp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
    AND CURRENT_DATE() )
GROUP BY
  pyver
ORDER BY
  num_downloads DESC
```
```
pyver	num_downloads
3.7	1305
NULL	382
3.6	297
2.7	104
3.8	102
3.9	95
3.5	50
3.4	22
```

(So that's <5% of kajiki users still on Python 2... let's consider them analogous to Windows XP users at this point)

So I think it's reasonable to make a backport release to the 0.8 release series if (and only if) the following conditions are met:

* The bug is major (either security or causes a crash)
* The bug affects Python 2.7 (If the bug only affects Python 3.4+, they should upgrade to 0.9+)
