### ISSUE TITLE
Kajiki needs a new owner?

### ISSUE THREAD

**Issue by nandoflorestan** [jackrosenthal/kajiki#56]
@amol- 

A few issues were added today by @jackrosenthal which are pretty essential for the health of the Kajiki project.  I am not coming back as a maintainer of Kajiki, but I know it deserves to be well maintained.  Essentially I wish to responsibly remove myself.  Are you interested in a transfer of ownership to you, or should we open this up for takers?

**Comment by jackrosenthal** [comment]
I don't mind helping out on maintaining ... ideally if we can have more than one person who can merge pull requests and make releases, it keeps the bus number down.

@amol- any interest in coordinating this?

**Comment by amol-** [comment]
Sorry for my late answer, have been dealing with some health issues those past weeks and couldn't chime in any earlier.

While I love kajiki as a project and I use it as my primary template engine I sadly do have to recognise that at the moment I wouldn't have the time to do a good job as the primary maintainer. I'll gladly review those PRs and continue contributing to it when I have a chance, but if anyone is willing to step up and take lead maintainership I'm more than happy to support.

**Comment by jackrosenthal** [comment]
I don't mind taking a lead here ... it's something new but I guess I love kajiki :)

**Comment by nandoflorestan** [comment]
@jackrosenthal 

Okay, I'd like you to inherit Kajiki, just as I got it from it original author, Rick Copeland.

What is your username in pypi?

Also I tried to transfer the github repository to you, but it errored out saying you already have a fork with the same name...  It might be necessary to delete that fork before we can do the transfer.

**Comment by jackrosenthal** [comment]
pypi username is "jmr"

Fork is deleted ... s/b ready to go for the transfer :)

**Comment by nandoflorestan** [comment]
@jackrosenthal 

Please delete me as an owner of kajiki in pypi.

I thank you in advance for all the code and Kajiki versions!

**Comment by jackrosenthal** [comment]
@nandoflorestan I accidentally let the transfer accept email expire (apparently they only last for 24h).

Can you try it again? Sorry about that...

**Comment by nandoflorestan** [comment]
@jackrosenthal 

You must be talking about the GitHub transfer, since the pypi thing worked and you are now a maintainer there.  So I just canceled the GitHub transfer and started it again.

Now will you please log in to pypi, go to https://pypi.org/manage/project/kajiki/collaboration/ and remove me?

Thanks!

**Comment by jackrosenthal** [comment]
Done and done (thanks again!).

Are you the owner of https://kajiki.readthedocs.io ? Any chance you can transfer that to me as well?

My username on readthedocs.org is jackrosenthal

**Comment by nandoflorestan** [comment]
@jackrosenthal 

I am not the owner of https://kajiki.readthedocs.io/ -- it must be either @rick446 or @amol-

**Comment by amol-** [comment]
that was me, added jack to readthedocs.

**Comment by jackrosenthal** [comment]
Thanks all! :)
