### ISSUE TITLE
kajiki IDE suppprt

### ISSUE THREAD

**Issue by elycheikhsmail** [jackrosenthal/kajiki#67]
is there ext for supporting kajiki template ?

**Comment by CastixGitHub** [comment]
for kajiki's xml templates, I'm using mhtml-mode in emacs
it colors the `py:` differently (does so with whatever namespace) but that's enough for me
maybe that can be a good starting point

**Comment by elycheikhsmail** [comment]
thank you 
I try to build static site generator on top of kajiki, I choose it kajiki template engine because it based xml then it will be easy to format and analyse by IDE like vscode
