### ISSUE TITLE
simple extends examples

### ISSUE THREAD

**Issue by elycheikhsmail** [jackrosenthal/kajiki#68]
I don't understand inhertence in kajiki template enginge, I learned and used inhertinence in jinja2 template engine I try the example in demo but I don't understand, I create this repo https://github.com/elycheikhsmail/kajiki-demo as demo for kajiki but I don't include inheritence (in official way)

**Comment by CastixGitHub** [comment]
https://docs.kajiki.io/xml-templates.html#inheritance-py-extends-py-block

https://jinja.palletsprojects.com/en/2.10.x/templates/#template-inheritance

what exactly didn't you understand?
basically you can override and extend blocks and functions

the parent template must be designed to be extended; in your demo repository it isn't.
(no blocks, no functions) (your child doesn't extend and doesn't have blocks either, be careful as literal can lead to security issues) (also your .gitignore doesn't work) (please consider using .xhtml or .kajiki extension for files) (honestly I don't get the point of your demo (currently))

here's the [implementation](https://github.com/jackrosenthal/kajiki/blob/master/kajiki/template.py#L124)
as you can see it just gets the module instance from the loader (so the second time it's already compiled and performant) and changes it's __globals__ values
and [here](https://github.com/jackrosenthal/kajiki/blob/1bd0e19ded0cae7f602d8e2a732b789f007c1767/kajiki/ir.py#L132)'s how the parent will be called once your template is converted to python code

**Comment by elycheikhsmail** [comment]
> https://docs.kajiki.io/xml-templates.html#inheritance-py-extends-py-block
> 
> https://jinja.palletsprojects.com/en/2.10.x/templates/#template-inheritance
> 
> what exactly didn't you understand? basically you can override and extend blocks and functions
> 
> the parent template must be designed to be extended; in your demo repository it isn't. (no blocks, no functions) (your child doesn't extend and doesn't have blocks either, be careful as literal can lead to security issues) (also your .gitignore doesn't work) (please consider using .xhtml or .kajiki extension for files) (honestly I don't get the point of your demo (currently))
> 
> here's the [implementation](https://github.com/jackrosenthal/kajiki/blob/master/kajiki/template.py#L124) as you can see it just gets the module instance from the loader (so the second time it's already compiled and performant) and changes it's **globals** values and [here](https://github.com/jackrosenthal/kajiki/blob/1bd0e19ded0cae7f602d8e2a732b789f007c1767/kajiki/ir.py#L132)'s how the parent will be called once your template is converted to python code

can you make simple demo of without dyninamic content(context) ?

**Comment by CastixGitHub** [comment]
can you give me an example using jinja2 blocks? I'll be happy to convert it if that can help

again, what do you find hard to understand? where do you see differences from jinja2 inheritance apart from syntax?

**Comment by elycheikhsmail** [comment]
> can you give me an example using jinja2 blocks? I'll be happy to convert it if that can help
> 
> again, what do you find hard to understand? where do you see differences from jinja2 inheritance apart from syntax?

Thank you for you help I will share an example using jinja2 I don't know how to convert it to kajiki

**Comment by elycheikhsmail** [comment]
I create simple static site generator based on kajiki and typer https://github.com/elycheikhsmail/py-static-site-generator but I mocked inheritenc please can you fix this
