### ISSUE TITLE
kajiki 0.9.2 requires python-3.11 according to linetable dependency

### ISSUE THREAD

**Issue by ondrejj** [jackrosenthal/kajiki#80]
It's unable to run kajiki 0.9.2 on python lower than 3.11. There is an requirement on linetable, which requires python3.11. Please, update dependencies and make linetable optional to fix older python compatibility.

**Comment by amol-** [comment]
Linetable does not apply any python version requirement. It should not prevent Kajiki to be installed on versions < 3.11 and kajiki will only invoke it if python is >= 3.11 ( https://github.com/jackrosenthal/kajiki/blob/0ba4979c6a28d424ccd84cbbce020ca40a67f1ba/kajiki/template.py#L393 )

That should also be confirmed by the fact that kajiki installs and passes unit tests on all verified Python versions -> https://github.com/jackrosenthal/kajiki/actions/runs/3543268336

So what problem are you exactly facing?

**Comment by ondrejj** [comment]
I can't build linetable for RHEL 9 (EPEL9). Unit tests fails. I also don't see any reason to install linetable for python<=3.10, because it's not used in kajiki. But unable to build current version of kajiki without linetable also on python 3.9.

Here is scratch build of linetable for EPEL9:
https://kojipkgs.fedoraproject.org//work/tasks/8979/98248979/build.log

May be linetable needs to be updated to be python < 3.11 compatible.

I built kajiki 0.9.2 without linetable with this patch:
https://src.fedoraproject.org/rpms/python-kajiki/blob/epel9/f/kajiki-no-linetable.diff

With this path kajiki should work with various versions of python.

**Comment by amol-** [comment]
linetable 0.0.3 has been released, this installs and works on Python3.9

**Comment by ondrejj** [comment]
No release on github yet. Please make a release. Thank you.
